/*
    STUDENT ACTIONS
*/
export const CHANGE_SIGNUP_PAGE = 'CHANGE_SIGNUP_PAGE';
export const SIGNUP_PAGE_FIELDS = 'SIGNUP_PAGE_FIELDS';
export const FETCH_SCHOOLS = 'FETCH_SCHOOLS';
export const REGISTER_STUDENT = 'REGISTER_STUDENT';
export const REGISTER_SCHOOL = 'REGISTER_SCHOOL';
export const FETCH_STUDENT = 'FETCH_STUDENT';
export const FETCH_REGISTER_REQUEST = 'FETCH_REGISTER_REQUEST';
export const APPROVE_REQUEST = 'APPROVE_REQUEST';
export const REJECT_REQUEST = 'REJECT_REQUEST';
export const STUDENT_UPDATE = 'STUDENT_UPDATE';
export const SCHOOL_UPDATE = 'SCHOOL_UPDATE';
export const STUDENT_LOGIN = 'STUDENT_LOGIN';
/*
    BUSINESS ACTIONS
*/
export const BUSINESS_LOGIN = 'BUSINESS_LOGIN';
export const BUSINESS_SIGNUP = 'BUSINESS_SIGNUP';
export const BUSINESS_FIELDS = 'BUSINESS_FIELDS';
export const BUSINESS_ADD = 'BUSINESS_ADD';
export const BUSINESS_LIST = 'BUSINESS_LIST';
export const FETCH_BUSINESS='FETCH_BUSINESS';
/*
    EVENT ACTIONS
*/
export const SCHEDULE_EVENT = 'SCHEDULE_EVENT';
export const ACTION_ON_EVENT = 'ACTION_ON_EVENT';
export const EVENT_LIST = 'EVENT_LIST';
export const EVENTS_SPONSER = 'EVENTS_SPONSER';
export const BUSINESS_UPDATE = 'BUSINESS_UPDATE';
/*
    DONATION ACTIONS
*/
export const ADD_DONATION = 'ADD_DONATION';
export const GET_DONATION = 'GET_DONATION';
export const EDIT_DONATION = 'EDIT_DONATION';
export const GET_EVENTS = 'GET_EVENTS';
export const GET_BUSINESS_BY_TOKEN = 'GET_BUSINESS_BY_TOKEN';
export const STUDENT_LOGGED_DATA = 'STUDENT_LOGGED_DATA';
export const LOG_OUT = 'LOG_OUT';
